export {default as Navigation} from './Navigation/Navigation'
export {default as PanelStatistic} from './Panels/PanelStatistic'
export {default as PanelTasks} from './Panels/PanelTasks'
export {default as PanelObservation} from './Panels/PanelObservation'
export {default as PanelTime} from './Panels/PanelTime'
export {default as PanelFacts} from './Panels/PanelFacts'
export {default as ButtonAddTask} from './Buttons/ButtonAddTask'
export {default as PanelNewTask} from './Panels/PanelNewTask'